web:
  image: nginx
  # volumes:
  #  - ./templates:/etc/nginx/templates
  ports:
   - "8080:80"
   - "443:443"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  volumes:
   - /certs:/etc/nginx/certs